{% set name = "nsidc-iceflow" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nsidc_iceflow-{{ version }}.tar.gz
  sha256: 3b450b116fd68294037a80f206bd4743bc6b3d4e5c6b450b9afbe874cafc0b67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - numpy >=2.0.1
    - earthaccess >=0.10.0
    - pandas >=2.2
    - h5py >=3.11
    - gps-timemachine >=1.1.4
    - pyproj >=3.6.1
    - shapely >=2.0.5
    - pandera >=0.20.3
    - pydantic >=2.8.2

test:
  imports:
    - nsidc.iceflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nsidc/iceflow
  summary: Harmonized access to (pre)OIB/IceSAT/IceSAT2 data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trey-stafford
    - mfisher87
